[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0 "
    max = "0.104.3"
    baseURL = "https://nijawi.netlify.app/"
    languageCode = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
